export const BUSINESSES = [
  {
    id: "1",
    avatar: "",
    business_owner: "Joseph Maduabuchi",
    business_name: "De-Light SuperStores",
    hyc_level: "TIER 3",
    phone_number: "+234 816 249 0242",
    business_type: "Merchant",
    date: "Aug 1,2026 at 09:15am",
    status: "active",
  },
  {
    id: "2",
    avatar: "",
    business_owner: "Amaka Okafor",
    business_name: "Amaka's Fashion Hub",
    hyc_level: "TIER 2",
    phone_number: "+234 803 112 3344",
    business_type: "Merchant",
    date: "Aug 2,2026 at 11:30am",
    status: "active",
  },
  {
    id: "3",
    avatar: "",
    business_owner: "Tunde Bakare",
    business_name: "Bakare Provisions",
    hyc_level: "TIER 1",
    phone_number: "+234 701 555 6677",
    business_type: "Agent",
    date: "Aug 3,2026 at 02:45pm",
    status: "inactive",
  },
  {
    id: "4",
    avatar: "",
    business_owner: "Chioma Nwosu",
    business_name: "Chioma's Beauty Store",
    hyc_level: "TIER 3",
    phone_number: "+234 805 998 7766",
    business_type: "Merchant",
    date: "July 15,2026 at 10:00am",
    status: "active",
  },
  {
    id: "5",
    avatar: "",
    business_owner: "Emeka Igbinedion",
    business_name: "Igbinedion Ventures",
    hyc_level: "TIER 2",
    phone_number: "+234 812 444 3322",
    business_type: "Agent",
    date: "July 20,2026 at 04:20pm",
    status: "inactive",
  },
  {
    id: "6",
    avatar: "",
    business_owner: "Funke Akindele",
    business_name: "Funke's Kitchen",
    hyc_level: "TIER 1",
    phone_number: "+234 706 888 9900",
    business_type: "Merchant",
    date: "July 28,2026 at 08:45am",
    status: "active",
  },
  {
    id: "7",
    avatar: "",
    business_owner: "Sade Balogun",
    business_name: "Balogun Textiles",
    hyc_level: "TIER 3",
    phone_number: "+234 818 222 1100",
    business_type: "Merchant",
    date: "May 19,2026 at 09:15am",
    status: "inactive",
  },
  {
    id: "8",
    avatar: "",
    business_owner: "Dele Momodu",
    business_name: "Momodu & Sons Electronics",
    hyc_level: "TIER 2",
    phone_number: "+234 809 656 5454",
    business_type: "Agent",
    date: "May 22,2026 at 01:10pm",
    status: "active",
  },
  {
    id: "9",
    avatar: "",
    business_owner: "Ifeoma Adebayo",
    business_name: "Ifeoma Pharmacy",
    hyc_level: "TIER 3",
    phone_number: "+234 703 777 8899",
    business_type: "Merchant",
    date: "June 5,2026 at 03:05pm",
    status: "active",
  },
  {
    id: "10",
    avatar: "",
    business_owner: "Kolawole Idris",
    business_name: "Kola Supermarket",
    hyc_level: "TIER 1",
    phone_number: "+234 814 321 0099",
    business_type: "Merchant",
    date: "July 31,2026 at 07:50pm",
    status: "inactive",
  },
];
