export const BUSINESSES = [
  {
    id: "1",
    avatar: "",
    business_owner: "Joseph Maduabuchi",
    business_name: "De-Light SuperStores",
    hyc_level: "TIER 3",
    phone_number: "+234 816 249 0242",
    business_type: "Merchant",
    date: "May 19,2026 at 09:15am",
  },
  {
    id: "2",
    avatar: "",
    business_owner: "Joseph Maduabuchi",
    business_name: "De-Light SuperStores",
    hyc_level: "TIER 3",
    phone_number: "+234 816 249 0242",
    business_type: "Merchant",
    date: "May 19,2026 at 09:15am",
  },
  {
    id: "3",
    avatar: "",
    business_owner: "Joseph Maduabuchi",
    business_name: "De-Light SuperStores",
    hyc_level: "TIER 3",
    phone_number: "+234 816 249 0242",
    business_type: "Merchant",
    date: "May 19,2026 at 09:15am",
  },
  {
    id: "4",
    avatar: "",
    business_owner: "Joseph Maduabuchi",
    business_name: "De-Light SuperStores",
    hyc_level: "TIER 3",
    phone_number: "+234 816 249 0242",
    business_type: "Merchant",
    date: "May 19,2026 at 09:15am",
  },
  {
    id: "5",
    avatar: "",
    business_owner: "Joseph Maduabuchi",
    business_name: "De-Light SuperStores",
    hyc_level: "TIER 3",
    phone_number: "+234 816 249 0242",
    business_type: "Merchant",
    date: "May 19,2026 at 09:15am",
  },
];
